kiosk/kiosk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import (
    RedirectView
)
from django.conf import settings
from store_app import views as store_app_views

urlpatterns = [
    url(r'^admin/logout/$', auth_views.logout, {'next_page': '/admin'}),
    url(r'^admin$', RedirectView.as_view(url='/admin/store_app/product/')),
    url(r'^admin/', admin.site.urls),
    url(r'^product_list/$', store_app_views.ProductList.as_view(), name="product_list"),
    url(r'^product_detail/(?P<pk>\d+)/$', store_app_views.ProductDetail.as_view(), name="product_detail"),
    # ,
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += [
    url(r'', RedirectView.as_view(url='/product_list/')),
]

kiosk/store_app/models.py
from django.db import models


class City(models.Model):
    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ('name',)
        unique_together = (('name',),)

    id = models.AutoField(primary_key=True, verbose_name='#')
    name = models.CharField(blank=False, null=False, max_length=100, verbose_name='Наименование', )

    def __str__(self):
        return '{x}'.format(x=self.name)


class Shop(models.Model):
    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = 'Магазины'
        ordering = ('name',)
        unique_together = (('name', 'city'), ('site',),)

    id = models.AutoField(primary_key=True, verbose_name='#')
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        verbose_name=City._meta.verbose_name.title())
    name = models.CharField(blank=False, null=False, max_length=100, verbose_name='Наименование магазина', )
    description = models.TextField(blank=True, null=True, max_length=200, verbose_name='Описание магазина', )
    site = models.URLField(blank=True, null=True, verbose_name='Сайт', )

    def __str__(self):
        return self.get_full_name()

    def get_name(self):
        return '{x}'.format(x=self.name)

    def get_full_name(self):
        return '{x} ({y})'.format(x=self.name, y=self.city.name)


class Attribute(models.Model):
    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'
        ordering = ('name',)
        unique_together = (('name',),)

    id = models.AutoField(primary_key=True, verbose_name='#')
    name = models.CharField(blank=False, null=False, max_length=100, verbose_name='Наименование характеристики', )

    def __str__(self):
        return '{x}'.format(x=self.name)


class Product(models.Model):
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('id',)
        unique_together = (('shop', 'url_at_shop',),)

    id = models.AutoField(primary_key=True, verbose_name='#')
    shop = models.ForeignKey(
        Shop,
        on_delete=models.CASCADE,
        verbose_name=Shop._meta.verbose_name.title()
    )
    name = models.CharField(blank=False, null=False, max_length=100, verbose_name='Наименование товара', )
    description = models.TextField(blank=False, null=False, max_length=200, verbose_name='Описание товара', )
    url_at_shop = models.URLField(blank=False, null=False, verbose_name='Ссылка на товар в магазине', )
    main_image_url = models.URLField(blank=False, null=False, verbose_name='Изображение товара', )
    attributes = models.ManyToManyField(
        Attribute, through='ProductAttributes',
        verbose_name=Attribute._meta.verbose_name_plural.title())

    def __str__(self):
        return 'ID:{x}, {y}'.format(x=self.id, y=self.name)


class ProductAttributes(models.Model):
    class Meta:
        verbose_name = 'Характеристики товара'
        verbose_name_plural = 'Характеристики товаров'
        ordering = ('-product__id', 'attribute__id',)
        unique_together = (('product', 'attribute'),)

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name=Product._meta.verbose_name.title())
    attribute = models.ForeignKey(
        Attribute,
        on_delete=models.CASCADE,
        verbose_name=Attribute._meta.verbose_name.title())
    value = models.CharField(blank=True, null=False, max_length=100, verbose_name='Значение', )

    def __str__(self):
        return '{x} / {y}: {z}'.format(
            x=self.product,
            y=self.attribute,
            z=self.value
        )

kiosk/store_app/views.py
from .models import Product
from django.views.generic import (
    ListView,
    DetailView,
)


class ProductList(ListView):
    model = Product


class ProductDetail(DetailView):
    model = Product

kiosk/store_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block html_head_title %}
        {% endblock %}
    </title>
</head>
<body>
{% block navigation %}
:: <a href="/admin">Aдминка</a> :: <a href="{% url 'product_list' %}">К общему списку</a> :: <br>
{% endblock %}
{% block html_body %}
{% endblock %}
</body>
</html>

kiosk/store_app/templates/store_app/base.html
{% extends 'base.html' %}

{% block html_head_title %}
STORE APP
{% endblock %}

kiosk/store_app/templates/store_app/error.html
{% extends 'base.html' %}

{% block html_head_title %}
404
{% endblock %}

{% block html_body %}
<br>
<br>
<br>
<h1>
    <center>
        <font color="green">In[0]:</font>
        <font color="#8333ff">sum</font>([item*<font color="blue">10</font>**i <font color="orange">for</font>
        i<font color="orange">,</font> item <font color="orange">in</font> <font color="#8333ff">enumerate</font>
        ([<font color="blue">2</font> ** <font color="blue">2</font><font color="orange">,</font> <font
            color="blue">0</font> * <font color="blue">0</font> ** <font color="blue">0</font><font
            color="orange">,</font> <font
            color="blue">2</font> ** <font color="blue">2</font>])])
    </center>
</h1>

{% endblock %}

kiosk/store_app/templates/store_app/product_detail.html
{% extends 'store_app/base.html' %}

{% block html_body %}
<center>
    <table width="800">
        <tr>
            <th>Изображение</th>
            <th>Подробное описание товара</th>
        </tr>
        <tr>
            <td><img width="300" src="{{ object.main_image_url }}"></td>
            <td>
                <b>Товар:</b><br>
                {{ object.name }}<br>
                <b>из магазина:</b><br>
                {{ object.shop }}<br>
                <b>Описание:</b><br>
                {{ object.description }} <br>
                <b>Характеристики товара:</b><br>
                <ul>
                    {% for product_attribute in object.productattributes_set.all %}
                    <li><b>{{ product_attribute.attribute.name }}:</b> {{ product_attribute.value }}</li>
                    {% endfor %}
                </ul>
                <br>
                <a href="{{ object.url_at_url }}" target="_blank">Перейти на сайт магазина</a> <br>
            </td>
        </tr>
    </table>
</center>
{% endblock %}

kiosk/store_app/templates/store_app/product_list.html
{% extends 'store_app/base.html' %}

{% block html_body %}
<center>
    <table width="800">
        <tr>
            <th>Изображение</th>
            <th>Описание товара</th>
        </tr>
        {% for product in object_list %}
        <tr>
            <td>
                <a href="{% url 'product_detail' product.id %}">
                    <img width="300" src="{{ product.main_image_url }}">
                </a>
            </td>
            <td>
                см. подробнее <a href="{% url 'product_detail' product.id %}">{{ product.name }}</a><br>
                <b>в магазине:</b><br>
                {{ product.shop }}<br>
                <b>ОПИСАНИЕ:</b><br>
                {{ product.description }} <br>
                <a href="{{ product.url_at_shop }}" target="_blank">Перейти на сайт магазина</a> <br>
            </td>
        </tr>
        {% endfor %}
    </table>
</center>
{% endblock %}